### ISSUE TITLE
Unable to open Plottr

### ISSUE THREAD

**Issue by sparklesandsoul** [cameronsutter/plottr_electron#147]
Hello there,
I ran into following issue:

Downloaded Plottr, unpacked it onto USB-stick. Hit the "plottr"-Icon to see if it works, it opened perfectly fine (and looked awesome). Closed it, changed the name of  folder "0.9.3." to "Timeline Tool Plottr". Copied and pasted the entire folder to my hard drive. If I start Plottr from USB-stick now, it won't open. If I start it from hard drive, it won't open either. Got an error-message, that "node.dll"-file was missing (it wasn't). I got that message twice, now it just won't open and not even give any error-message. Deleted all files and started all new, just to be sure: restarted computer, downloaded .zip again, unpacked it again onto my hard drive. Still doesn't work.
Not sure if I did something wrong or it's some sort of bug. Would be glad to receive some help in any case, the programme looks amazing and I can't wait to work with it. :)

Keep up the good work!
Cheers
PS: Sorry for any mistakes, I'm not a native speaker.

**Comment by cameronsutter** [comment]
Thanks so much for trying out Plottr! Your English is great for a non-native speaker! Where are you from?

I'm sorry you're having problems. It sounds like something weird has happened. In the next version this will be much easier; there is going to be a real installer so you won't have to worry about zip folders and all that.

Have you tried unpacking to the USB-stick again? Also, instead of just deleting files, you might need to uninstall the program from Windows. You can do that in settings. Just search for `Uninstall/change Programs`. After you uninstall it completely, try unzipping and opening it again.

Let me know if any of that helps. I hope you can get it working.

**Comment by sparklesandsoul** [comment]
Hey Cameron,
thanks a lot for the fast reply and the lovely compliment, I am from Germany! :)
I didn't manage to uninstall Plottr, it's not even listed in the installed programms of my computer, so there is literally nothing to unsinstall from my Windows.
I unzipped the file again onto my USB-drive, still doesn't work.
Don't worry tho, I'll just wait for the next version and update you if it's working then. I think this problem might very possibly solve itself with the new version, as you said yourself. I am patient - I'll wait. ;)
Warm Greetings

**Comment by cameronsutter** [comment]
Germany, cool!

I'm sorry you have to wait for the next version. I'm trying to get it done quickly :)

Thanks for being patient. Good luck writing

**Comment by cameronsutter** [comment]
@sparklesandsoul have you tried out the new version yet? Has it been working for you? Let me know if you have any issues. Thanks
